# Generated by Django 3.1.1 on 2021-02-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AliasTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreatActor', models.CharField(max_length=30)),
                ('Alias', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ThreatActor', models.CharField(max_length=30)),
                ('FilePath', models.FileField(upload_to='Files/')),
            ],
        ),
        migrations.CreateModel(
            name='SourceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatActorTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreatActor', models.CharField(max_length=30)),
            ],
        ),
    ]
