# Generated by Django 3.1.1 on 2021-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0002_filedetails_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='User',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
