# Generated by Django 3.1.1 on 2021-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_filedetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='Defination',
            field=models.CharField(default=1, max_length=1200),
            preserve_default=False,
        ),
    ]
