# Generated by Django 3.1.1 on 2021-03-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_mispgalaxies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AVModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('FilePath', models.FileField(upload_to='Files/')),
            ],
        ),
    ]
