# Generated by Django 3.1.1 on 2021-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_avmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avmodel',
            name='FilePath',
            field=models.FileField(upload_to='AV/'),
        ),
    ]
